# -*- coding: utf-8 -*-
"""aitask4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rFsOEbeoutd-r_3GhDwaYm3_F65uLhFS
"""

import math

class Hexagon:
    def __init__(self, cnic_last_digit):
        self.side_length = cnic_last_digit
        self.angle = 120

    def calcArea(self):
        return 1.5 * 1.732 * self.side_length

    def calcPeri(self):
        return 6 * self.side_length

    def calcAngleSum(self):
        return 6 * self.angle

    def display(self):
        print("Hexagon:")
        print("Area:", self.calcArea())
        print("Perimeter:", self.calcPeri())
        print("Sum of Angles:", self.calcAngleSum())

class Square:
    def __init__(self, cnic_last_digit):
        self.side_length = cnic_last_digit + 1

    def calcAreaSquare(self):
        return self.side_length ** 2

    def calcPeriSquare(self):
        return 4 * self.side_length

    def display(self):
        print("Square:")
        print("Area:", self.calcAreaSquare())
        print("Perimeter:", self.calcPeriSquare())

def main():
    cnic = input("Enter the last digit of your CNIC: ")
    cnic_last_digit = int(cnic[-1])

    hexagon = Hexagon(cnic_last_digit)
    square = Square(cnic_last_digit)

    while True:
        print("\nMenu:")
        print("1. Hexagon")
        print("2. Square")
        print("3. Exit")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            hexagon.display()
        elif choice == '2':
            square.display()
        elif choice == '3':
            print("Exiting program. Goodbye!")
            break
        else:
            print("Invalid input. Please enter 1, 2, or 3.")

if __name__ == "__main__":
    main()

